### ISSUE TITLE
[question] possible duplicate

### ISSUE THREAD

**Issue by rthomazel** [splitgraph/yarn-plugin-pin-deps#1]
I'm using this plugin with yarn 3, and when I run it I get some info output

```bash
YN0000: Possible duplicate: typescript:5.1.6 has 2 candidates (1 conflicting pairs) in workspace
```

unsure how to fix it :) If this is a yarn issue/help request please let me know

thanks! I  love pinning deps :)

**Comment by milesrichardson** [comment]
Hey! Sorry, just seeing this, didn't realize people used the plugin 😅 

You can ignore this, it's expected. It's because of this weird thing Yarn does where it patches the TypeScript install after every major Yarn version. I forget the exact reason but if you search the Yarn repo you can probably find relevant issues.

tl;dr safe to ignore that warning

**Comment by rthomazel** [comment]
Ok got it :) 

so that warning is from yarn after all?

**Comment by milesrichardson** [comment]
the warning is from the plug-in, but it's caused by the hacky patch that every version of yarn applies to typescript
